name: google_sign_in_dart_example
description: Example app for google_sign_in_dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  url_launcher: ^5.5.0
  googleapis: ^0.55.0
  extension_google_sign_in_as_googleapis_auth: ^1.0.0

  google_sign_in: ^4.5.3
  google_sign_in_dartio:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true